- name: configure Nginx LB
  hosts: Nginx
  become: true
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: present

    - name: config nginx
      template:
        src: /home/ubuntu/roles/Nginx/templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: Restart Nginx

    - name: Check Nginx configuration
      command: sudo nginx -t
      register: nginx_test
      ignore_errors: true

    - name: Reload Nginx if configuration is valid
      systemd:
        name: nginx
        state: reloaded
      when: nginx_test.rc == 0

handlers:
  - name: Restart Nginx
    service:
      name: nginx
      state: restarted